default: &default
  host: localhost
  adapter: postgresql
  encoding: UTF8
  username: timbel
  timeout: 5000
  reaping_frequency: 30
  pool: 5

development:
  <<: *default
  database: sinatra_seq_dev
  password: kuvvek777tim

test:
  <<: *default
  database: sinatra_seq_test
  password: kuvvek777tim

production:
  <<: *default
  database: sinatra_seq_prod
  password: kuvvek777tim